### ISSUE TITLE
Support typescript definition

### ISSUE THREAD

**Issue by hados99** [CrystalComputerCorp/smpte-timecode#12]
Hi, really thanks for good module.

I need typescript definition of smpte-timecode,
but there's no typescript definition.

So I'll do this for next week (maybe), is it encouraged PR to this repo?
or should I do PR to  [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by m1tk4** [comment]
If your PR doesn't break the tests and doesn't decrease the coverage I would appreciate it here. Thank you!

**Comment by hados99** [comment]
I made PR to Definitely Typed last week and merged.
it can be installed (when it is typescript project) by ``` npm i -D @types/smpte-timecode```
https://www.npmjs.com/package/@types/smpte-timecode

Thank you!

**Comment by m1tk4** [comment]
great, thank you.
