### ISSUE TITLE
Converting to seconds?

### ISSUE THREAD

**Issue by pietrop** [CrystalComputerCorp/smpte-timecode#13]
Hello,
Thanks for the great module!

I am using it to make an ADL (Audio Decision List) converter ([`aes31-adl-composer`](https://github.com/bbc/aes31-adl-composer)).

As far as I can tell, converting to seconds, is not part of the `smpte-timecode` module?

To convert to seconds I modified [this example on stackoverflow](https://stackoverflow.com/questions/31385418/convert-timecode-to-seconds).

```js
const tcToSec = (timecode) =>{
	const hours   = timecode.hours * 60 * 60;
	const minutes = timecode.minutes * 60;
	const seconds = timecode.seconds;
	const frames  = timecode.frames *(1/timecode.frameRate);
	const totalTime = hours + minutes + seconds + frames;

	return totalTime;
};
```

But was wondering if there is already a way to do this as part of the module that I might have missed? or whether there might be interest in a PR to add the functionality?

**Comment by m1tk4** [comment]
Wouldn't timecode.frameCount/timecode.frameRate be easier?
