### ISSUE TITLE
Support dropframe < 2

### ISSUE THREAD

**Issue by aliasdhacker** [CrystalComputerCorp/smpte-timecode#22]
We are getting submissions by end users with a dropframe of 1 -- While this doesn't make sense to me, since you need a dropframe of 2 to even out the difference between 29.97 and 30 fps, these users are still having submissions rejected due to validation errors on "dropframe 1" ( "00:04:00;01", 29.97)

They are requesting I change the smpte-timecode source to not fail on ;01.  I have changed it locally, but I don't know if this is a good idea.  

Thoughts??  Thanks in advance for your time!

Change is here, "1" instead of "2" for "this.frames"
        if (this.hours > 23 || this.minutes > 59 || this.seconds > 59 || this.frames >= this.frameRate ||
            (this.dropFrame && this.seconds === 0 && this.minutes % 10 && this.frames < 1 * (this.frameRate / 29.97))) {
            throw new Error("Invalid timecode" + JSON.stringify(timeCode));
        }

**Comment by m1tk4** [comment]
The time code of 4 minutes 0 seconds 1 frame is not a valid timecode for drop-frame 29.97 rates.
