### ISSUE TITLE
Regex doesn't work with timecode 20+ hours

### ISSUE THREAD

**Issue by casperwarnich** [CrystalComputerCorp/smpte-timecode#30]
`timeCode = "20:04:16:24";`
`var parts = timeCode.match('^([0-23]|[01]\\d):(\\d\\d):(\\d\\d)(:|;|\\.)(\\d\\d)$');`
`console.log(parts) // null`

`timeCode = "19:04:16:24";`
`var parts = timeCode.match('^([0-23]|[01]\\d):(\\d\\d):(\\d\\d)(:|;|\\.)(\\d\\d)$');`
`console.log(parts) // ["19:04:16:24","19","04","16",":","24"]`

I made a new regex that seems to work:

`timeCode = "20:04:16:24";`
`var parts = timeCode.match('^([0-9]|[0][0-9]|[1][0-9]|[2][0-3]):(\\d\\d):(\\d\\d)(:|;|\\.)(\\d\\d)$');`
`console.log(parts) // ["20:04:16:24","20","04","16",":","24"]`

**Comment by m1tk4** [comment]
Do you mind submitting this as a pull request? Thanks.

**Comment by m1tk4** [comment]
I am looking at https://github.com/CrystalComputerCorp/smpte-timecode/pull/31/commits/f0d8378a77840b34d4254c690b2dd97c96ad304b and the original Regexp there is different from what you have above.  At the first glance what's in the code right now should handle hours > 20.

Do you have a test that shows that the library is not performing according to the expectations?

**Comment by casperwarnich** [comment]
Oh, I seem to have forgotten I was using a forked repo with the addition of allowing timecodes starting with only one digit instead of two (i.e. 8 instead of 08).
So I'm the one who made the none working regex :-D 
So sorry.

**Comment by m1tk4** [comment]
No worries!
