### ISSUE TITLE
NPM registry version mismatch

### ISSUE THREAD

**Issue by nukemonk** [CrystalComputerCorp/smpte-timecode#33]
First I thought I went crazy, but it seems that the source in this Github repository does not match with the code of the NPM package. Even though the package.json here has version `1.2.3`, and the version on npmjs.com also has `1.2.3`. Check the following two links for comparison:

[NPM registry smpte-timecode.js line 57](https://www.npmjs.com/package/smpte-timecode/v/1.2.3?activeTab=explore#:~:text=this.hours%20%3D%20timeCode.hours%3B)
[Github smpte-timecode.js line 57](https://github.com/CrystalComputerCorp/smpte-timecode/blob/b8edceefe29c162447fdb9e4d452dbec743aecfe/smpte-timecode.js#L57)

**Comment by m1tk4** [comment]
No you're not crazy. I need to add sync to NPM to Github CI. Should be there along with 1.3 release. I'll keep this open until this is fixed.

**Comment by m1tk4** [comment]
resolved w 1.3.1 publish. Thanks and apologies.
