### ISSUE TITLE
Support for 3 Digit Frame Rates?

### ISSUE THREAD

**Issue by vincentdory** [CrystalComputerCorp/smpte-timecode#38]
Hello, I have an issue with this project when I try to create a time code that has a frame rate that is 3 digits in length (200 in my specific case). 

The issue appears to be happening at line 66 of smpte-timecode.js, when I am trying to create a timecode object. The call looks like this: `stc('16:12:45:180', '200.00')`

This is the portion of the code throwing the error:

`var parts = timeCode.match('^([012]\\d):(\\d\\d):(\\d\\d)(:|;|\\.)(\\d\\d)$');
 if (!parts) throw new Error("Timecode string expected as HH:MM:SS:FF or HH:MM:SS;FF");`

The "Timecode string expected as HH:MM:SS:FF or HH:MM:SS;FF" is the error being thrown. The timecode I am trying to make looks like this, and has the previously mentioned frame rate of 200: **16:12:45:180**. So the issue is the frame number of the timecode, which is 3 digits in length when the regex check is expecting only 2 digits.

Would it be possible to also allow 3 digit frame rates in this regex check, and would there be any other issues with allowing these high frame rate time codes in other parts of the code?

Thanks!

**Comment by m1tk4** [comment]
this is resolved in v.1.3.4, thank you!

**Comment by vincentdory** [comment]
Hello, thanks for fixing this! Do you know when you will be able to formally release 1.3.4? My npm can't find this new version when I try to update to 1.3.4.

**Comment by m1tk4** [comment]
apologies, I missed somehting in packaging. 1.3.5 is now released and on NPM.
