### ISSUE TITLE
Date Conversion Issue

### ISSUE THREAD

**Issue by cliffplaysdrums** [CrystalComputerCorp/smpte-timecode#4]
### Issue
There appears to be an issue with consistency when converting to a date.

In the attached image, I constructed a Timecode object using an existing Timecode object's toDate() function. The frame counts differ by 1 frame each time.

This happens with and without drop frames (also demonstrated).

![timecode_issue](https://user-images.githubusercontent.com/17258650/43083151-d454d96c-8e63-11e8-835e-e0284878ff60.png)

### Environment
I copy-pasted  smpte-timecode.js into an online Javascript tester - https://repl.it/repls/DarkvioletWeeQueenalexandrasbirdwing

**Comment by m1tk4** [comment]
should be resolved by the merge
