### ISSUE TITLE
Support needed for more fractional frame rates

### ISSUE THREAD

**Issue by vincentdory** [CrystalComputerCorp/smpte-timecode#40]
Hello again,

My team is encountering an issue with making a timecode with a fractional frame rate that does not seem to be currently supported by this project. We tried to create a time code with a frame rate of 239.76, but got back the error message found [here](https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L54), it appears that the issue is happening on [this line](https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L45). 

Would you be able to add additional support to this library for more fractional frame rates? 

Thanks!

**Comment by m1tk4** [comment]
@vincentdory ,

Please try expressing 239.76 as natural fraction, i.e.

```JS
var nineHundredFrames = new Timecode(900,[240000,1001],true);
```

If this doesn't work, please attach a sample of your code triggering the error and reopen this issue. 

Thank you!
