### ISSUE TITLE
Timecode Generation with Drop Frame Rate

### ISSUE THREAD

**Issue by vincentdory** [CrystalComputerCorp/smpte-timecode#42]
Hello,

I'm not sure if this is intentional or unintentional behavior, but i'm running into an issue when I created a timecode with this library. 

When I create a timecode like this: `stc(461734, 59.94, false)`, what i'm expecting back is a timecode that looks like: `02:08:23:18`.

However, the returned timecode is instead `02:08:23;18`, which isn't correct because timecode isn't supposed to be drop frame.

This issue isn't occurring when I set the frame rate to an array with a numerator/denominator, and it seems that the issue is occuring at [this line](https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L49), which is setting a timecode to be drop frame if it is a fractional frame rate that isn't 23.98 (which is 24 when rounded up). Is this expected behavior, or is it possible to modify that line to not override the drop frame value of the time code if an argument for it is provided to the Timecode constructor?

Thanks!

**Comment by m1tk4** [comment]
this is indeed a bug. https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L19 should have been executed after the frame rate initialization block.

Please use numerator/denominator frame rate initializer as a workaround, I'll try to get this resolved this weekend. Thank you for reporting this.

**Comment by vincentdory** [comment]
Hello, thanks for replying. 

Do you know when you will be able to address this issue?

**Comment by m1tk4** [comment]
fixed in https://github.com/CrystalComputerCorp/smpte-timecode/commit/254c147129e592e79e6cd093ddad4ef1dcb05771
