### ISSUE TITLE
Input format to prevent error

### ISSUE THREAD

**Issue by adamjw3** [CrystalComputerCorp/smpte-timecode#5]
Whats the best way to set the input format?

```
<Input 
                  placeholder="In"
                  autoFocus={true}
                  onChange={e => this.onChange(e)} 
                  type="time"
                  step="00.01" 
                  pattern="^(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)?([0-5]?\d)$"
                  style={{fontSize: "16px", width: "100%"}}/>
              )}
```

```
onChange = (element, frameRate) => {
    const { form } = this.props;
    const keys = form.getFieldValue('keys');

    keys.forEach(function (value) {
      var inTc = Timecode(form.getFieldValue('1-in'), 25); // errors
      console.log(inTc.toString());
    });
```

This keeps resulting in the following
Error: Timecode string expected as HH:MM:SS:FF or HH:MM:SS;FF

**Comment by m1tk4** [comment]
Check out https://gist.github.com/allensarkisyan/5441601 . You may have to narrow it down to 25fps case though. Also, the constructor that takes a string in expects 00:00:15:01 for 15 sec 1 frame - i.e. you can't omit the leading zeroes for hours or minutes.

**Comment by m1tk4** [comment]
Also, your issue may be due to input type="time" trimming the frame count off. Try outputting getFieldValue() return value to the console.
